apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: dev-on-k-s
build:
  artifacts:
  - image: myservice
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: local
  deploy:
    kustomize:
      paths:
      - k8s/overlay/local
