apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice
spec:
  template:
    spec:
      containers:
        - env:
            - name: NAME
              value: local
          name: myservice
